# Generated by Django 6.0 on 2025-12-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_visit_lat_visit_lng_visit_location_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('WAITING', 'รอ'), ('CALLED', 'เรียกแล้ว'), ('OPD_DONE', 'ตรวจเสร็จสิ้น'), ('FOLLOWUP', 'นัดติดตาม'), ('CANCELLED', 'ยกเลิก')], default='WAITING', max_length=10),
        ),
    ]
