# Generated by Django 6.0 on 2026-05-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_queue_monitoring_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageresult',
            name='ai_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
