# Generated by Django 6.0 on 2026-06-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_triageresult_ai_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paired_at', models.DateTimeField(auto_now_add=True)),
                ('unpaired_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='queues.device')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='queues.visit')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'is_active'], name='queues_devi_device__e4cf29_idx'), models.Index(fields=['visit', 'is_active'], name='queues_devi_visit_i_32d2be_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device',), name='unique_active_assignment_per_device'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('visit',), name='unique_active_assignment_per_visit')],
            },
        ),
    ]
