# Generated by Django 6.0 on 2026-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0008_deviceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageresult',
            name='nurse_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='pain_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='urgent_symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
