# Generated by Django 6.0 on 2026-06-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0009_triageresult_nurse_note_vitalsign_pain_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='exam_room',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
