# Generated by Django 6.0 on 2026-06-08 19:09

from django.db import migrations, models


def migrate_waiting_to_waiting_queue(apps, schema_editor):
    Queue = apps.get_model("queues", "Queue")
    Visit = apps.get_model("queues", "Visit")

    waiting_visit_ids = list(
        Queue.objects.filter(status="WAITING").values_list("visit_id", flat=True)
    )
    Queue.objects.filter(status="WAITING").update(status="WAITING_QUEUE")

    for visit in Visit.objects.filter(id__in=waiting_visit_ids, confirmed_at__isnull=True):
        visit.confirmed_at = visit.triaged_at or visit.registered_at
        visit.save(update_fields=["confirmed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0010_queue_exam_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('WAITING_VITALS', 'Waiting vitals'), ('WAITING_CONFIRMATION', 'Waiting confirmation'), ('WAITING_QUEUE', 'Waiting queue'), ('WAITING', 'Waiting'), ('CALLED', 'Called'), ('MONITORING', 'Monitoring'), ('OPD_DONE', 'OPD Done'), ('FOLLOWUP', 'Follow-up'), ('DISCHARGED', 'Discharged'), ('CANCELLED', 'Cancelled')], default='WAITING_VITALS', max_length=24),
        ),
        migrations.AlterField(
            model_name='visit',
            name='final_severity',
            field=models.CharField(blank=True, choices=[('RED', 'แดง'), ('YELLOW', 'เหลือง'), ('GREEN', 'เขียว')], max_length=10, null=True),
        ),
        migrations.RunPython(migrate_waiting_to_waiting_queue, migrations.RunPython.noop),
    ]
