# Generated by Django 6.0 on 2026-06-16 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0011_visit_confirmed_at_alter_queue_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_O2', 'Low SpO2'), ('LOW_BP', 'Low systolic BP'), ('HIGH_RR', 'High respiratory rate')], max_length=24)),
                ('severity', models.CharField(default='RED', max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('value', models.FloatField(blank=True, null=True)),
                ('threshold', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(blank=True, default='vitals', max_length=32)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_critical_alerts', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_alerts', to='queues.visit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='queues_crit_status_55a48d_idx'), models.Index(fields=['visit', 'status'], name='queues_crit_visit_i_15d578_idx'), models.Index(fields=['alert_type', 'status'], name='queues_crit_alert_t_5b8a79_idx')],
            },
        ),
    ]
