# Generated by Django 4.2.24 on 2026-07-09 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_appointment_attended_at_appointment_status_and_more'),
        ('queues', '0012_criticalalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(max_length=50)),
                ('patient_identifier', models.CharField(max_length=50)),
                ('device_db_id', models.IntegerField(blank=True, db_column='device_id', null=True)),
                ('patient_db_id', models.IntegerField(blank=True, db_column='patient_id', null=True)),
                ('heart_rate', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_sys', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_dia', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_identifier', 'created_at'], name='queues_iotv_device__e34e63_idx'), models.Index(fields=['patient_identifier', 'created_at'], name='queues_iotv_patient_d84c96_idx'), models.Index(fields=['patient_db_id', 'created_at'], name='queues_iotv_patient_53d99b_idx')],
            },
        ),
    ]
