# Generated by Django 6.0 on 2026-07-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0013_alter_criticalalert_id_alter_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotvital',
            name='device_db_id',
            field=models.BigIntegerField(blank=True, db_column='device_id', null=True),
        ),
        migrations.AlterField(
            model_name='iotvital',
            name='patient_db_id',
            field=models.BigIntegerField(blank=True, db_column='patient_id', null=True),
        ),
    ]
