# Generated by Django 6.0 on 2026-09-01 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_staff_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    StaffProfile = apps.get_model('queues', 'StaffProfile')
    StaffProfile.objects.bulk_create(
        [StaffProfile(user_id=user_id, role='STAFF') for user_id in User.objects.values_list('id', flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0019_staffduty_nursecareassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffduty',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DOCTOR', 'แพทย์'), ('NURSE', 'พยาบาล'), ('NURSE_ASSISTANT', 'ผู้ช่วยพยาบาล'), ('EMERGENCY', 'เจ้าหน้าที่ฉุกเฉิน'), ('STAFF', 'เจ้าหน้าที่')], default='STAFF', max_length=24)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__first_name', 'user__username'],
            },
        ),
        migrations.RunPython(create_existing_staff_profiles, migrations.RunPython.noop),
    ]
