# Generated by Django 6.0 on 2026-09-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0020_staffduty_is_available_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to='staff_photos/%Y/%m/'),
        ),
    ]
