# Generated by Django 6.0 on 2026-09-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0021_staffprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticalalert',
            name='alert_type',
            field=models.CharField(choices=[('LOW_O2', 'Low SpO2'), ('LOW_BP', 'Low systolic BP'), ('HIGH_RR', 'High respiratory rate'), ('HIGH_HEART_RATE', 'High heart rate'), ('LOW_HEART_RATE', 'Low heart rate'), ('HIGH_TEMPERATURE', 'High temperature')], max_length=24),
        ),
    ]
