# Generated by Django 6.0 on 2026-09-15 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0022_alter_criticalalert_alert_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'จัดเวรแล้ว'), ('LEAVE', 'ลา'), ('CANCELLED', 'ยกเลิกเวร')], default='SCHEDULED', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_schedules', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shift_date', 'start_time', 'user__first_name', 'user__username'],
                'indexes': [models.Index(fields=['shift_date', 'status'], name='queues_shif_shift_d_8f1038_idx'), models.Index(fields=['user', 'shift_date'], name='queues_shif_user_id_2995d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'shift_date', 'start_time'), name='unique_staff_shift_start')],
            },
        ),
    ]
