# Generated by Django 6.0 on 2026-09-17 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0024_alter_staffprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_expedited',
            field=models.BooleanField(db_index=True, default=False, help_text='ลัดลำดับภายในระดับความเร่งด่วนเดิม โดยไม่เปลี่ยนผลคัดกรอง'),
        ),
        migrations.AddField(
            model_name='queue',
            name='manual_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='เลขคิวที่เจ้าหน้าที่กำหนดเอง หากว่างจะใช้เลขอัตโนมัติ', null=True),
        ),
        migrations.CreateModel(
            name='VisitWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VITALS_RECORDED', 'บันทึกสัญญาณชีพ'), ('TRIAGE_CONFIRMED', 'ยืนยันผลคัดกรอง'), ('QUEUE_EXPEDITED', 'ลัดลำดับคิว'), ('QUEUE_RESTORED', 'คืนลำดับคิวปกติ'), ('QUEUE_NUMBER_CHANGED', 'เปลี่ยนเลขคิว'), ('QUEUE_CALLED', 'เรียกเข้าห้องตรวจ'), ('DOCTOR_ASSESSMENT', 'แพทย์บันทึกผลตรวจ')], db_index=True, max_length=32)),
                ('actor_name', models.CharField(blank=True, default='', max_length=180)),
                ('actor_role', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_workflow_logs', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='queues.visit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['visit', '-created_at'], name='queues_visi_visit_i_464d8d_idx')],
            },
        ),
    ]
