# Generated by Django 6.0 on 2026-09-27 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0037_alter_visitworkflowlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('BUZZER', 'Identify patient with buzzer')], max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pending delivery'), ('DELIVERED', 'Delivered to device'), ('ACKNOWLEDGED', 'Completed by device'), ('FAILED', 'Failed on device'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_count', models.PositiveSmallIntegerField(default=0)),
                ('result_message', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='queues.device')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_device_commands', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_commands', to='queues.visit')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'status', 'created_at'], name='queues_devi_device__aaf18b_idx')],
            },
        ),
    ]
