# Generated by Django 6.0 on 2026-10-02 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0041_alter_visitworkflowlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='superseded_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Visit ใหม่ที่เริ่มแทนกระบวนการเดิมในกรณีเร่งด่วน', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_visits', to='queues.visit'),
        ),
    ]
