# Generated by Django 6.0 on 2025-12-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0004_visit_lat_visit_lng_visit_location_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_at', models.DateTimeField()),
                ('clinic', models.CharField(blank=True, default='', max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'นัดหมาย'), ('COMPLETED', 'สำเร็จ'), ('CANCELED', 'ยกเลิก')], default='SCHEDULED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='queues.visit')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.CharField(blank=True, default='', max_length=255)),
                ('pain_score', models.IntegerField(blank=True, null=True)),
                ('fbs', models.FloatField(blank=True, null=True)),
                ('k', models.FloatField(blank=True, null=True)),
                ('mg', models.FloatField(blank=True, null=True)),
                ('hct', models.FloatField(blank=True, null=True)),
                ('ga_weeks', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_assessment', to='queues.visit')),
            ],
        ),
    ]
