# Generated by Django 6.0 on 2025-12-24 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
        ('queues', '0004_visit_lat_visit_lng_visit_location_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalassessment',
            name='visit',
        ),
        migrations.CreateModel(
            name='VisitAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.CharField(blank=True, max_length=255, null=True)),
                ('pain_score', models.IntegerField(blank=True, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('next_appointment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opd_assessment', to='queues.visit')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='ClinicalAssessment',
        ),
    ]
