# Generated by Django 6.0 on 2025-12-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_remove_clinicalassessment_visit_visitassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitassessment',
            name='age_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='อายุ (ปี)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='bp_dia',
            field=models.IntegerField(blank=True, null=True, verbose_name='BP Dia'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='bp_sys',
            field=models.IntegerField(blank=True, null=True, verbose_name='BP Sys'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='bt_c',
            field=models.FloatField(blank=True, null=True, verbose_name='BT (°C)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='child_under5',
            field=models.BooleanField(default=False, verbose_name='เด็กอายุต่ำกว่า 5 ปี'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='epilepsy',
            field=models.BooleanField(default=False, verbose_name='Epilepsy'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='fbs_mg',
            field=models.FloatField(blank=True, null=True, verbose_name='FBS (mg%)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='ga_weeks',
            field=models.IntegerField(blank=True, null=True, verbose_name='GA (weeks)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='immunocompromised',
            field=models.BooleanField(default=False, verbose_name='ภูมิต้านทานต่ำ'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='immunocompromised_detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดภูมิต้านทานต่ำ'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='is_monk',
            field=models.BooleanField(default=False, verbose_name='พระภิกษุ/สามเณร'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='lab_hct',
            field=models.FloatField(blank=True, null=True, verbose_name='Hct (vol%)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='lab_k',
            field=models.FloatField(blank=True, null=True, verbose_name='K (mEq/L)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='lab_mg',
            field=models.FloatField(blank=True, null=True, verbose_name='Mg (mEq/L)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='opd_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='opd_urgency',
            field=models.CharField(choices=[('RED', 'เร่งด่วนสีแดง'), ('YELLOW', 'เร่งด่วนสีเหลือง'), ('NORMAL', 'ปกติ')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='pregnant',
            field=models.BooleanField(default=False, verbose_name='ตั้งครรภ์'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='pulmonary_tb_mplus_incomplete',
            field=models.BooleanField(default=False, verbose_name='Pulmonary TB M+ กินยาไม่ครบ 2 เดือน'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='red_blood_transfusion',
            field=models.BooleanField(default=False, verbose_name='มารับเลือด'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='red_copd_asthma_dyspnea',
            field=models.BooleanField(default=False, verbose_name='Known COPD/Asthma หายใจไม่อิ่ม (ไม่เข้า ER)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='red_nonvenomous_animal_bite',
            field=models.BooleanField(default=False, verbose_name='ถูกสัตว์ไม่มีพิษกัด/ข่วน (ไม่เข้า ER)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='red_relative_anxiety',
            field=models.BooleanField(default=False, verbose_name='ญาติวิตกกังวลมาก (พยาบาลนำประวัติพบแพทย์)'),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='red_severe_fatigue',
            field=models.BooleanField(default=False, verbose_name='เหนื่อยเพลียมาก (พยาบาลนำประวัติพบแพทย์)'),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='chief_complaint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='อาการสำคัญ'),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='วินิจฉัย'),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='next_appointment_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='นัดครั้งถัดไป'),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='pain_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pain score (0-10)'),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='treatment',
            field=models.TextField(blank=True, null=True, verbose_name='การรักษา/คำแนะนำ'),
        ),
    ]
