# Generated by Django 6.0 on 2025-12-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_visitassessment_age_years_visitassessment_bp_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitassessment',
            name='age_years',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='bp_dia',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='bp_sys',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='bt_c',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='child_under5',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='fbs_mg',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='immunocompromised',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='immunocompromised_detail',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='is_monk',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='note',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='pulmonary_tb_mplus_incomplete',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='red_blood_transfusion',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='red_copd_asthma_dyspnea',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='red_nonvenomous_animal_bite',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='red_relative_anxiety',
        ),
        migrations.RemoveField(
            model_name='visitassessment',
            name='red_severe_fatigue',
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='anxious_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='blood_receive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='bt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='child_under_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='dia_bp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='fbs',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='known_copd_asthma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='low_immunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='low_immunity_detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='monk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='next_appointment_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='non_toxic_bite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='pulmonary_tb_mplus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='sys_bp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitassessment',
            name='very_fatigue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='chief_complaint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='epilepsy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='ga_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='lab_hct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='lab_k',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='lab_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='next_appointment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='pain_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='treatment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
