# Generated by Django 6.0 on 2025-12-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0004_remove_visitassessment_age_years_and_more'),
        ('queues', '0005_alter_queue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitassessment',
            name='followup_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_assessment', to='queues.visit'),
        ),
    ]
