# Generated by Django 6.0 on 2026-05-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_visitassessment_followup_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitassessment',
            name='opd_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
