# Generated by Django 6.0 on 2026-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0009_opd_downstream_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pharmacy_skipped',
            field=models.BooleanField(default=False, help_text='บันทึกเมื่อแพทย์เลือกส่งการเงินโดยไม่ส่งใบสั่งยา', verbose_name='แพทย์ยืนยันว่าไม่มีรายการยา'),
        ),
    ]
