# Generated by Django 6.0 on 2026-09-30 08:05

from django.db import migrations, models
from django.db.models import F


def backfill_open_billing_queue(apps, schema_editor):
    Bill = apps.get_model("opd", "Bill")
    Bill.objects.filter(
        billing_queue_entered_at__isnull=True,
        status__in=("DRAFT", "READY", "WAIVED"),
        paid_at__isnull=True,
    ).update(billing_queue_entered_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0010_bill_pharmacy_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billing_queue_entered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_open_billing_queue, migrations.RunPython.noop),
    ]
