# Generated by Django 6.0 on 2026-10-01 07:50

from django.db import migrations, models
from django.db.models.functions import Coalesce


def backfill_pharmacy_queue_entry_time(apps, schema_editor):
    Prescription = apps.get_model("opd", "Prescription")
    Prescription.objects.filter(
        status__in=["SENT", "PREPARING", "READY"],
        pharmacy_queue_entered_at__isnull=True,
    ).update(pharmacy_queue_entered_at=Coalesce("sent_at", "created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0011_bill_billing_queue_entered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billing_queue_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='billing_queue_skipped_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_queue_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_queue_entered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_queue_skipped_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_pharmacy_queue_entry_time, migrations.RunPython.noop),
    ]
