# Generated by Django 6.0 on 2026-10-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0012_bill_billing_queue_called_at_and_more'),
        ('queues', '0041_alter_visitworkflowlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รอสรุปค่าใช้จ่าย'), ('READY', 'รอชำระเงิน'), ('PAID', 'ชำระแล้ว'), ('WAIVED', 'ไม่มีค่าใช้จ่ายผู้ป่วย'), ('CANCELLED', 'ยกเลิก'), ('TRANSFERRED', 'โอนยอดค้างไปรวมบิลใหม่')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.CreateModel(
            name='BillBalanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance_transfer', to='opd.bill')),
                ('target_visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carried_balance_transfers', to='queues.visit')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_balance_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
