# Generated by Django 6.0 on 2026-06-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_district_patient_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_relationship',
            field=models.CharField(blank=True, choices=[('FATHER', 'พ่อ'), ('MOTHER', 'แม่'), ('SPOUSE', 'คู่สมรส'), ('CHILD', 'บุตร'), ('SIBLING', 'พี่น้อง'), ('RELATIVE', 'ญาติ'), ('FRIEND', 'เพื่อน'), ('CAREGIVER', 'ผู้ดูแล'), ('OTHER', 'อื่น ๆ')], default='', max_length=20),
        ),
    ]
