# Generated by Django 6.0 on 2026-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_emergency_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ATTENDED', 'Attended'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=16),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
